name: Flutter Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows
      - name: Zip built files
        run: |
          cd build/windows/runner/Release
          tar -czvf artifact.zip ./*
  
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-windows-artifact
          path: build/windows/runner/Release/artifact.zip



